# -*- coding: utf-8 -*-
#Ilport of QT module

import B2d_XML
from PyQt4 import QtCore, QtGui
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)
#import of  the different list used#
#List contains in Subject_study.csv file
#The list is stored in the variable : subjectchoice
file_subject=open('Subject_study.csv', 'r')
subjectchoice=[]
for i in range(0,int(file_subject.readline())+1):
    subjectchoice.append(file_subject.readline().rstrip('\n'))#.rstrip('\n')
file_subject.close()
#List contains in Project_study.csv file
#The list is stored in the variable : projectchoice
file_project=open('Project_phase.csv', 'r')
projectchoice=[]
for i in range(0,int(file_project.readline())+1):
    projectchoice.append(file_project.readline().rstrip('\n'))
file_project.close()
#List contains in Location.csv file
#The list is stored in the variable : locationchoice
file_location=open('Location.csv', 'r')
locationchoice=[]
for i in range(0,int(file_location.readline())+1):
    locationchoice.append(file_location.readline().rstrip('\n'))
file_location.close()
#List contains in Variable.csv file
#The list is stored in the variable : variablechoice
file_variable=open('Variable.csv', 'r')
variablechoice=[]
for i in range(0,int(file_variable.readline())+1):
    variablechoice.append(file_variable.readline().rstrip('\n'))
file_variable.close()
#List contains in Format.csv file
#The list is stored in the variable : formatchoice
file_format=open('Format.csv', 'r')
formatchoice=[]
for i in range(0,int(file_format.readline())+1):
    formatchoice.append(file_format.readline().rstrip('\n'))
file_format.close()
A=0

use_lim='' #Comme ces valeurs ne sont pas obligatoires, on est obligés de les initialiser car elles sont utilisés dans la fonction B2d_XML
process=''
citation=''
class Ui_MainDialog(object):
    def setupUi(self, MainDialog):
        MainDialog.setObjectName(_fromUtf8("MainDialog"))
        MainDialog.resize(945, 634)
        self.gridLayout = QtGui.QGridLayout(MainDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.pushButton_quit = QtGui.QPushButton(MainDialog)
        self.pushButton_quit.setObjectName(_fromUtf8("pushButton_quit"))
        self.gridLayout.addWidget(self.pushButton_quit, 1, 1, 1, 1)
        self.tabWidget = QtGui.QTabWidget(MainDialog)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_ID = QtGui.QWidget()
        self.tab_ID.setObjectName(_fromUtf8("tab_ID"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_ID)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 6, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 3, 2, 1, 1)
        self.Language = QtGui.QLabel(self.tab_ID)
        self.Language.setObjectName(_fromUtf8("Language"))
        self.gridLayout_3.addWidget(self.Language, 7, 0, 1, 1)
        self.pushButton_Next1 = QtGui.QPushButton(self.tab_ID)
        self.pushButton_Next1.setObjectName(_fromUtf8("pushButton_Next1"))
        self.gridLayout_3.addWidget(self.pushButton_Next1, 9, 3, 1, 1)
        self.English = QtGui.QLabel(self.tab_ID)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(True)
        font.setKerning(False)
        self.English.setFont(font)
        self.English.setObjectName(_fromUtf8("English"))
        self.gridLayout_3.addWidget(self.English, 7, 2, 1, 1)
        self.textEdit_abstract = QtGui.QTextEdit(self.tab_ID)
        self.textEdit_abstract.setObjectName(_fromUtf8("textEdit_abstract"))
        self.gridLayout_3.addWidget(self.textEdit_abstract, 2, 2, 1, 1)
        self.lineEdit_title = QtGui.QLineEdit(self.tab_ID)
        self.lineEdit_title.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_title.setObjectName(_fromUtf8("lineEdit_title"))
        self.gridLayout_3.addWidget(self.lineEdit_title, 0, 2, 1, 1)
        self.Title = QtGui.QLabel(self.tab_ID)
        self.Title.setObjectName(_fromUtf8("Title"))
        self.gridLayout_3.addWidget(self.Title, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 9, 2, 1, 1)
        self.Data_type = QtGui.QLabel(self.tab_ID)
        self.Data_type.setObjectName(_fromUtf8("Data_type"))
        self.gridLayout_3.addWidget(self.Data_type, 5, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 8, 2, 1, 1)
        self.comboBox_Datatype = QtGui.QComboBox(self.tab_ID)
        self.comboBox_Datatype.setObjectName(_fromUtf8("comboBox_Datatype"))
        self.comboBox_Datatype.addItem(_fromUtf8(""))
        self.comboBox_Datatype.addItem(_fromUtf8(""))
        self.comboBox_Datatype.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.comboBox_Datatype, 5, 2, 1, 1)
        self.Abstract = QtGui.QLabel(self.tab_ID)
        self.Abstract.setObjectName(_fromUtf8("Abstract"))
        self.gridLayout_3.addWidget(self.Abstract, 2, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem5, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab_ID, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setEnabled(False)
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox_time = QtGui.QGroupBox(self.tab_2)
        self.groupBox_time.setObjectName(_fromUtf8("groupBox_time"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_time)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.dateEdit_tempend = QtGui.QDateEdit(self.groupBox_time)
        self.dateEdit_tempend.setObjectName(_fromUtf8("dateEdit_tempend"))
        self.gridLayout_6.addWidget(self.dateEdit_tempend, 0, 6, 1, 1)#♥
        self.Tempend = QtGui.QLabel(self.groupBox_time)
        self.Tempend.setObjectName(_fromUtf8("Tempend"))
        self.gridLayout_6.addWidget(self.Tempend, 0, 5, 1, 1)
        self.dateEdit_date = QtGui.QDateEdit(self.groupBox_time)
        self.dateEdit_date.setObjectName(_fromUtf8("dateEdit_date"))
        self.gridLayout_6.addWidget(self.dateEdit_date, 1, 2, 1, 1)
        self.date1 = QtGui.QLabel(self.groupBox_time)
        self.date1.setObjectName(_fromUtf8("date1"))
        self.gridLayout_6.addWidget(self.date1, 1, 1, 1, 1)
        spacerItem28 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem28, 0, 3, 1, 1)
        spacerItem29 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem29, 0, 6, 1, 1)
        self.Tempstart = QtGui.QLabel(self.groupBox_time)
        self.Tempstart.setObjectName(_fromUtf8("Tempstart"))
        self.gridLayout_6.addWidget(self.Tempstart, 0, 1, 1, 1)
        self.radioButton_date = QtGui.QRadioButton(self.groupBox_time)
        self.radioButton_date.setObjectName(_fromUtf8("radioButton_date"))
        self.gridLayout_6.addWidget(self.radioButton_date, 1, 0, 1, 1)
        self.dateEdit_tempstart = QtGui.QDateEdit(self.groupBox_time)
        self.dateEdit_tempstart.setObjectName(_fromUtf8("dateEdit_tempstart"))
        self.gridLayout_6.addWidget(self.dateEdit_tempstart, 0, 2, 1, 1)
        self.timeEdit_start = QtGui.QTimeEdit(self.groupBox_time)
        self.timeEdit_start.setObjectName(_fromUtf8("timeEdit_start"))
        self.gridLayout_6.addWidget(self.timeEdit_start, 0, 3, 1, 1)
#        spacerItem_time = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
#        self.gridLayout_6.addItem(spacerItem_time, 0, 4, 1, 1)
        self.timeEdit_end = QtGui.QTimeEdit(self.groupBox_time)
        self.timeEdit_end.setObjectName(_fromUtf8("timeEdit_end"))
        self.gridLayout_6.addWidget(self.timeEdit_end, 0, 7, 1, 1)
        spacerItem_time2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem_time2, 0, 8, 1, 1)
        self.timeEdit_date = QtGui.QTimeEdit(self.groupBox_time)
        self.timeEdit_date.setObjectName(_fromUtf8("timeEdit_date"))
        self.gridLayout_6.addWidget(self.timeEdit_date, 1, 3, 1, 1)
        self.radioButton_temp = QtGui.QRadioButton(self.groupBox_time)
        self.radioButton_temp.setObjectName(_fromUtf8("radioButton_temp"))
        self.gridLayout_6.addWidget(self.radioButton_temp, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_time, 5, 0, 1, 3)
        self.groupBox_geo = QtGui.QGroupBox(self.tab_2)
        self.groupBox_geo.setObjectName(_fromUtf8("groupBox_geo"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_geo)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.doubleSpinBox_depth1 = QtGui.QDoubleSpinBox(self.groupBox_geo)
        self.doubleSpinBox_depth1.setMaximum(500)
        self.doubleSpinBox_depth1.setMinimum(-6000)
        self.doubleSpinBox_depth1.setObjectName(_fromUtf8("doubleSpinBox_depth1"))
        self.gridLayout_5.addWidget(self.doubleSpinBox_depth1, 4, 1, 1, 1)
        self.Depth2 = QtGui.QLabel(self.groupBox_geo)
        self.Depth2.setObjectName(_fromUtf8("Depth2"))
        self.gridLayout_5.addWidget(self.Depth2, 4, 4, 1, 1)
        self.doubleSpinBox_depth2 = QtGui.QDoubleSpinBox(self.groupBox_geo)
        self.doubleSpinBox_depth2.setMaximum(0.0)
        self.doubleSpinBox_depth2.setMinimum(-6000)
        self.doubleSpinBox_depth2.setProperty("value", 0.0)
        self.doubleSpinBox_depth2.setObjectName(_fromUtf8("doubleSpinBox_depth2"))
        self.gridLayout_5.addWidget(self.doubleSpinBox_depth2, 4, 5, 1, 1)
        self.Depth1 = QtGui.QLabel(self.groupBox_geo)
        self.Depth1.setObjectName(_fromUtf8("Depth1"))
        self.gridLayout_5.addWidget(self.Depth1, 4, 0, 1, 1)
        self.doubleSpinBox_North = QtGui.QDoubleSpinBox(self.groupBox_geo)
        self.doubleSpinBox_North.setMinimum(-90.0)
        self.doubleSpinBox_North.setMaximum(90.0)
        self.doubleSpinBox_North.setProperty("value", 48.94)
        self.doubleSpinBox_North.setObjectName(_fromUtf8("doubleSpinBox_North"))
        self.gridLayout_5.addWidget(self.doubleSpinBox_North, 1, 1, 1, 1)
        self.doubleSpinBox_South1 = QtGui.QDoubleSpinBox(self.groupBox_geo)
        self.doubleSpinBox_South1.setMinimum(-90.0)
        self.doubleSpinBox_South1.setMaximum(90.0)
        self.doubleSpinBox_South1.setProperty("value", 48.93)
        self.doubleSpinBox_South1.setObjectName(_fromUtf8("doubleSpinBox_South1"))
        self.gridLayout_5.addWidget(self.doubleSpinBox_South1, 1, 5, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem6, 1, 7, 1, 1)
        self.doubleSpinBox_West = QtGui.QDoubleSpinBox(self.groupBox_geo)
        self.doubleSpinBox_West.setMinimum(-180.0)
        self.doubleSpinBox_West.setMaximum(180.0)
        self.doubleSpinBox_West.setProperty("value", 7.86)
        self.doubleSpinBox_West.setObjectName(_fromUtf8("doubleSpinBox_West"))
        self.gridLayout_5.addWidget(self.doubleSpinBox_West, 2, 1, 1, 1)
        self.comboBox_ref_geo = QtGui.QComboBox(self.groupBox_geo)
        self.comboBox_ref_geo.setObjectName(_fromUtf8("comboBox_ref_geo"))
        self.comboBox_ref_geo.addItem(_fromUtf8(""))
        self.comboBox_ref_geo.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.comboBox_ref_geo, 0, 1, 1, 5)
        self.doubleSpinBox_East = QtGui.QDoubleSpinBox(self.groupBox_geo)
        self.doubleSpinBox_East.setMinimum(-180.0)
        self.doubleSpinBox_East.setMaximum(180.0)
        self.doubleSpinBox_East.setProperty("value", 7.87)
        self.doubleSpinBox_East.setObjectName(_fromUtf8("doubleSpinBox_East"))
        self.gridLayout_5.addWidget(self.doubleSpinBox_East, 2, 5, 1, 1)
        self.North = QtGui.QLabel(self.groupBox_geo)
        self.North.setObjectName(_fromUtf8("North"))
        self.gridLayout_5.addWidget(self.North, 1, 0, 1, 1)
        self.Coordinate_system = QtGui.QLabel(self.groupBox_geo)
        self.Coordinate_system.setObjectName(_fromUtf8("Coordinate_system"))
        self.gridLayout_5.addWidget(self.Coordinate_system, 0, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem7, 1, 3, 1, 1)
        self.degreeEast1 = QtGui.QLabel(self.groupBox_geo)
        self.degreeEast1.setObjectName(_fromUtf8("degreeEast1"))
        self.gridLayout_5.addWidget(self.degreeEast1, 2, 2, 1, 1)
        self.South = QtGui.QLabel(self.groupBox_geo)
        self.South.setObjectName(_fromUtf8("South"))
        self.gridLayout_5.addWidget(self.South, 1, 4, 1, 1)
        self.degreeNord2 = QtGui.QLabel(self.groupBox_geo)
        self.degreeNord2.setObjectName(_fromUtf8("degreeNord2"))
        self.gridLayout_5.addWidget(self.degreeNord2, 1, 6, 1, 1)
        self.degreeast2 = QtGui.QLabel(self.groupBox_geo)
        self.degreeast2.setObjectName(_fromUtf8("degreeast2"))
        self.gridLayout_5.addWidget(self.degreeast2, 2, 6, 1, 1)
        self.degreeN1 = QtGui.QLabel(self.groupBox_geo)
        self.degreeN1.setObjectName(_fromUtf8("degreeN1"))
        self.gridLayout_5.addWidget(self.degreeN1, 1, 2, 1, 1)
        self.East = QtGui.QLabel(self.groupBox_geo)
        self.East.setObjectName(_fromUtf8("East"))
        self.gridLayout_5.addWidget(self.East, 2, 0, 1, 1)
        self.West = QtGui.QLabel(self.groupBox_geo)
        self.West.setObjectName(_fromUtf8("West"))
        self.gridLayout_5.addWidget(self.West, 2, 4, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_geo, 1, 0, 1, 3)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem8, 2, 0, 1, 1)
        self.pushButton_next2 = QtGui.QPushButton(self.tab_2)
        self.pushButton_next2.setObjectName(_fromUtf8("pushButton_next2"))
        self.gridLayout_4.addWidget(self.pushButton_next2, 10, 2, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 10, 1, 1, 1)
        self.pushButton_previous2 = QtGui.QPushButton(self.tab_2)
        self.pushButton_previous2.setObjectName(_fromUtf8("pushButton_previous2"))
        self.gridLayout_4.addWidget(self.pushButton_previous2, 10, 0, 1, 1)
        self.Creation_date = QtGui.QLabel(self.tab_2)
        self.Creation_date.setObjectName(_fromUtf8("Creation_date"))
        self.gridLayout_4.addWidget(self.Creation_date, 8, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem10, 0, 0, 1, 1)
        self.dateEdit_creation_date = QtGui.QDateEdit(self.tab_2)
        self.dateEdit_creation_date.setDate(QtCore.QDate.currentDate())
        self.dateEdit_creation_date.setObjectName(_fromUtf8("dateEdit_creation_date"))
        self.gridLayout_4.addWidget(self.dateEdit_creation_date, 8, 1, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem11, 9, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem12, 6, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setEnabled(False)
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem13, 15, 2, 1, 1)
        self.ISO = QtGui.QLabel(self.tab_3)
        self.ISO.setObjectName(_fromUtf8("ISO"))
        self.gridLayout_7.addWidget(self.ISO, 14, 0, 1, 1)
        self.Nongeodataset = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(True)
        font.setKerning(False)
        self.Nongeodataset.setFont(font)
        self.Nongeodataset.setObjectName(_fromUtf8("Nongeodataset"))
        self.gridLayout_7.addWidget(self.Nongeodataset, 14, 3, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem14, 3, 1, 1, 1)
        self.GeoscientificInformation = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(True)
        font.setKerning(False)
        self.GeoscientificInformation.setFont(font)
        self.GeoscientificInformation.setObjectName(_fromUtf8("GeoscientificInformation"))
        self.gridLayout_7.addWidget(self.GeoscientificInformation, 14, 1, 1, 1)
        self.Theme = QtGui.QLabel(self.tab_3)
        self.Theme.setObjectName(_fromUtf8("Theme"))
        self.gridLayout_7.addWidget(self.Theme, 14, 2, 1, 1)
        self.Subject_study = QtGui.QLabel(self.tab_3)
        self.Subject_study.setObjectName(_fromUtf8("Subject_study"))
        self.gridLayout_7.addWidget(self.Subject_study, 1, 0, 1, 1)
        self.listWidget_subjectStudy2 = QtGui.QListWidget(self.tab_3)
        self.listWidget_subjectStudy2.setObjectName(_fromUtf8("listWidget_subjectStudy2"))
        self.gridLayout_7.addWidget(self.listWidget_subjectStudy2, 1, 3, 2, 1)
        self.pushButton_subjectStudy_out = QtGui.QPushButton(self.tab_3)
        self.pushButton_subjectStudy_out.setObjectName(_fromUtf8("pushButton_subjectStudy_out"))
        self.gridLayout_7.addWidget(self.pushButton_subjectStudy_out, 2, 2, 1, 1)
        self.pushButton_projectPhasein = QtGui.QPushButton(self.tab_3)
        self.pushButton_projectPhasein.setObjectName(_fromUtf8("pushButton_projectPhasein"))
        self.gridLayout_7.addWidget(self.pushButton_projectPhasein, 4, 2, 1, 1)
        self.pushButton_previous3 = QtGui.QPushButton(self.tab_3)
        self.pushButton_previous3.setObjectName(_fromUtf8("pushButton_previous3"))
        self.gridLayout_7.addWidget(self.pushButton_previous3, 15, 0, 1, 1)
        self.pushButton_projectPhaseout = QtGui.QPushButton(self.tab_3)
        self.pushButton_projectPhaseout.setObjectName(_fromUtf8("pushButton_projectPhaseout"))
        self.gridLayout_7.addWidget(self.pushButton_projectPhaseout, 5, 2, 1, 1)
        self.pushButton_locationin = QtGui.QPushButton(self.tab_3)
        self.pushButton_locationin.setObjectName(_fromUtf8("pushButton_locationin"))
        self.gridLayout_7.addWidget(self.pushButton_locationin, 8, 2, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem15, 10, 1, 1, 1)
        self.Variable = QtGui.QLabel(self.tab_3)
        self.Variable.setObjectName(_fromUtf8("Variable"))
        self.gridLayout_7.addWidget(self.Variable, 12, 0, 1, 1)
        self.pushButton_next3 = QtGui.QPushButton(self.tab_3)
        self.pushButton_next3.setObjectName(_fromUtf8("pushButton_next3"))
        self.gridLayout_7.addWidget(self.pushButton_next3, 15, 4, 1, 1)
        self.Location = QtGui.QLabel(self.tab_3)
        self.Location.setObjectName(_fromUtf8("Location"))
        self.gridLayout_7.addWidget(self.Location, 8, 0, 2, 1)
        self.pushButton_variableout = QtGui.QPushButton(self.tab_3)
        self.pushButton_variableout.setObjectName(_fromUtf8("pushButton_variableout"))
        self.gridLayout_7.addWidget(self.pushButton_variableout, 12, 2, 1, 1)
        self.pushButton_subjectstudy_in = QtGui.QPushButton(self.tab_3)
        self.pushButton_subjectstudy_in.setObjectName(_fromUtf8("pushButton_subjectstudy_in"))
        self.gridLayout_7.addWidget(self.pushButton_subjectstudy_in, 1, 2, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem16, 6, 1, 1, 1)
        self.pushButton_variablein = QtGui.QPushButton(self.tab_3)
        self.pushButton_variablein.setObjectName(_fromUtf8("pushButton_variablein"))
        self.gridLayout_7.addWidget(self.pushButton_variablein, 11, 2, 1, 1)
        self.listWidget_variable1 = QtGui.QListWidget(self.tab_3)
        self.listWidget_variable1.setObjectName(_fromUtf8("listWidget_variable1"))
        ##
        for i in range(0, len(variablechoice)-1) :
            item = QtGui.QListWidgetItem()
            self.listWidget_variable1.addItem(item)         
        self.gridLayout_7.addWidget(self.listWidget_variable1, 11, 1, 2, 1)
        self.listWidget_subjectStudy1 = QtGui.QListWidget(self.tab_3)
        self.listWidget_subjectStudy1.setObjectName(_fromUtf8("listWidget_subjectStudy1"))
        ##
        for i in range(0, len(subjectchoice)-1) :
            item = QtGui.QListWidgetItem()
            self.listWidget_subjectStudy1.addItem(item)
        self.gridLayout_7.addWidget(self.listWidget_subjectStudy1, 1, 1, 2, 1)
        self.listWidget_projectPhase1 = QtGui.QListWidget(self.tab_3)
        self.listWidget_projectPhase1.setObjectName(_fromUtf8("listWidget_projectPhase1"))
        ##
        for i in range(0, len(projectchoice)-1) :
            item = QtGui.QListWidgetItem()
            self.listWidget_projectPhase1.addItem(item)
        self.gridLayout_7.addWidget(self.listWidget_projectPhase1, 4, 1, 2, 1)
        self.pushButton_locationout = QtGui.QPushButton(self.tab_3)
        self.pushButton_locationout.setObjectName(_fromUtf8("pushButton_locationout"))
        self.gridLayout_7.addWidget(self.pushButton_locationout, 9, 2, 1, 1)
        self.Project_phase = QtGui.QLabel(self.tab_3)
        self.Project_phase.setObjectName(_fromUtf8("Project_phase"))
        self.gridLayout_7.addWidget(self.Project_phase, 4, 0, 1, 1)
        self.listWidget_Location1 = QtGui.QListWidget(self.tab_3)
        self.listWidget_Location1.setObjectName(_fromUtf8("listWidget_Location1"))
        ##
        for i in range(0, len(locationchoice)-1) :
            item = QtGui.QListWidgetItem()
            self.listWidget_Location1.addItem(item)
        self.gridLayout_7.addWidget(self.listWidget_Location1, 8, 1, 2, 1)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem17, 13, 1, 1, 1)
        self.listWidget_projectPhase2 = QtGui.QListWidget(self.tab_3)
        self.listWidget_projectPhase2.setObjectName(_fromUtf8("listWidget_projectPhase2"))
        self.gridLayout_7.addWidget(self.listWidget_projectPhase2, 4, 3, 2, 1)
        self.listWidget_Location2 = QtGui.QListWidget(self.tab_3)
        self.listWidget_Location2.setObjectName(_fromUtf8("listWidget_Location2"))
        self.gridLayout_7.addWidget(self.listWidget_Location2, 8, 3, 2, 1)
        self.listWidget_variable2 = QtGui.QListWidget(self.tab_3)
        self.listWidget_variable2.setObjectName(_fromUtf8("listWidget_variable2"))
        self.gridLayout_7.addWidget(self.listWidget_variable2, 11, 3, 2, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setEnabled(False)
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.Format = QtGui.QLabel(self.tab_4)
        self.Format.setObjectName(_fromUtf8("Format"))
        self.gridLayout_8.addWidget(self.Format, 1, 0, 2, 1)
        self.lineEdit_quality = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_quality.setObjectName(_fromUtf8("lineEdit_quality"))
        self.gridLayout_8.addWidget(self.lineEdit_quality, 4, 2, 1, 5)
        self.textEdit_process = QtGui.QTextEdit(self.tab_4)
        self.textEdit_process.setObjectName(_fromUtf8("textEdit_process"))
        self.gridLayout_8.addWidget(self.textEdit_process, 6, 2, 1, 5)
        self.pushButton_next4 = QtGui.QPushButton(self.tab_4)
        self.pushButton_next4.setObjectName(_fromUtf8("pushButton_next4"))
        self.gridLayout_8.addWidget(self.pushButton_next4, 7, 7, 1, 1)
        self.listWidget_Format1 = QtGui.QListWidget(self.tab_4)
        self.listWidget_Format1.setObjectName(_fromUtf8("listWidget_Format1"))
        ##
        for i in range(0, len(formatchoice)-1) :
            item = QtGui.QListWidgetItem()
            self.listWidget_Format1.addItem(item)
        self.gridLayout_8.addWidget(self.listWidget_Format1, 1, 2, 2, 1)
        self.pushButton_Formatin = QtGui.QPushButton(self.tab_4)
        self.pushButton_Formatin.setObjectName(_fromUtf8("pushButton_Formatin"))
        self.gridLayout_8.addWidget(self.pushButton_Formatin, 1, 4, 1, 1)
        self.Quality = QtGui.QLabel(self.tab_4)
        self.Quality.setObjectName(_fromUtf8("Quality"))
        self.gridLayout_8.addWidget(self.Quality, 4, 0, 1, 1)
        self.process=QtGui.QLabel(self.tab_4)
        self.process.setObjectName(_fromUtf8("Processing"))
        self.gridLayout_8.addWidget(self.process, 6, 0, 1, 1)
        self.pushButton_previous4 = QtGui.QPushButton(self.tab_4)
        self.pushButton_previous4.setObjectName(_fromUtf8("pushButton_previous4"))
        self.gridLayout_8.addWidget(self.pushButton_previous4, 7, 0, 1, 1)
        self.pushButton_formatout = QtGui.QPushButton(self.tab_4)
        self.pushButton_formatout.setObjectName(_fromUtf8("pushButton_formatout"))
        self.gridLayout_8.addWidget(self.pushButton_formatout, 2, 4, 1, 1)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem18, 3, 2, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem19, 5, 0, 1, 1)
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem20, 0, 0, 1, 1)
        self.listWidget_Format2 = QtGui.QListWidget(self.tab_4)
        self.listWidget_Format2.setObjectName(_fromUtf8("listWidget_Format2"))
        self.gridLayout_8.addWidget(self.listWidget_Format2, 1, 6, 2, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setEnabled(False)
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.lineEdit_useLimitation = QtGui.QLineEdit(self.tab_5)
        self.lineEdit_useLimitation.setObjectName(_fromUtf8("lineEdit_useLimitation"))
        self.gridLayout_9.addWidget(self.lineEdit_useLimitation, 1, 2, 1, 1)
        self.textEdit_Citation = QtGui.QTextEdit(self.tab_5)
        self.textEdit_Citation.setObjectName(_fromUtf8("textEdit_Citation"))
        self.gridLayout_9.addWidget(self.textEdit_Citation, 6, 2, 1, 1)
        self.pushButton_next5 = QtGui.QPushButton(self.tab_5)
        self.pushButton_next5.setObjectName(_fromUtf8("pushButton_next5"))
        self.gridLayout_9.addWidget(self.pushButton_next5, 8, 4, 1, 1)
        spacerItem21 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem21, 2, 0, 1, 1)
        spacerItem22 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem22, 0, 0, 1, 1)
        self.Acces = QtGui.QLabel(self.tab_5)
        self.Acces.setObjectName(_fromUtf8("Acces"))
        self.gridLayout_9.addWidget(self.Acces, 4, 0, 1, 1)
        self.Citation = QtGui.QLabel(self.tab_5)
        self.Citation.setObjectName(_fromUtf8("Citation"))
        self.gridLayout_9.addWidget(self.Citation, 6, 0, 1, 1)
        self.pushButton_previous5 = QtGui.QPushButton(self.tab_5)
        self.pushButton_previous5.setObjectName(_fromUtf8("pushButton_previous5"))
        self.gridLayout_9.addWidget(self.pushButton_previous5, 8, 0, 1, 1)
        self.Use_limitation = QtGui.QLabel(self.tab_5)
        self.Use_limitation.setObjectName(_fromUtf8("Use_limitation"))
        self.gridLayout_9.addWidget(self.Use_limitation, 1, 0, 1, 1)
        self.comboBox_access = QtGui.QComboBox(self.tab_5)
        self.comboBox_access.setObjectName(_fromUtf8("comboBox_access"))
        self.comboBox_access.addItem(_fromUtf8(""))
        self.comboBox_access.addItem(_fromUtf8(""))
        self.comboBox_access.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.comboBox_access, 4, 2, 1, 1)
        spacerItem23 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem23, 5, 0, 1, 1)
        spacerItem24 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem24, 7, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setEnabled(False)
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem25, 8, 1, 1, 1)
        self.groupBox_resourceContact = QtGui.QGroupBox(self.tab_6)
        self.groupBox_resourceContact.setObjectName(_fromUtf8("groupBox_resourceContact"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_resourceContact)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.ResourceOrganisation = QtGui.QLabel(self.groupBox_resourceContact)
        self.ResourceOrganisation.setObjectName(_fromUtf8("ResourceOrganisation"))
        self.horizontalLayout_2.addWidget(self.ResourceOrganisation)
        self.comboBox_resourcOrganisation = QtGui.QComboBox(self.groupBox_resourceContact)
        self.comboBox_resourcOrganisation.setObjectName(_fromUtf8("comboBox_resourcOrganisation"))
        self.comboBox_resourcOrganisation.addItem(_fromUtf8(""))
        self.comboBox_resourcOrganisation.addItem(_fromUtf8(""))
        self.comboBox_resourcOrganisation.addItem(_fromUtf8(""))
        self.comboBox_resourcOrganisation.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.comboBox_resourcOrganisation)
        self.gridLayout_10.addWidget(self.groupBox_resourceContact, 4, 0, 1, 4)
        self.pushButton_next6 = QtGui.QPushButton(self.tab_6)
        self.pushButton_next6.setObjectName(_fromUtf8("pushButton_next6"))
        self.gridLayout_10.addWidget(self.pushButton_next6, 8, 3, 1, 1)
        self.pushButton_previous6 = QtGui.QPushButton(self.tab_6)
        self.pushButton_previous6.setObjectName(_fromUtf8("pushButton_previous6"))
        self.gridLayout_10.addWidget(self.pushButton_previous6, 8, 0, 1, 1)
        self.groupBox_distributor = QtGui.QGroupBox(self.tab_6)
        self.groupBox_distributor.setObjectName(_fromUtf8("groupBox_distributor"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_distributor)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.Organization_distributor = QtGui.QLabel(self.groupBox_distributor)
        self.Organization_distributor.setObjectName(_fromUtf8("Organization_distributor"))
        self.horizontalLayout.addWidget(self.Organization_distributor)
        self.comboBox_distributor = QtGui.QComboBox(self.groupBox_distributor)
        self.comboBox_distributor.setObjectName(_fromUtf8("comboBox_distributor"))
        self.comboBox_distributor.addItem(_fromUtf8(""))
        self.comboBox_distributor.addItem(_fromUtf8(""))
        self.comboBox_distributor.addItem(_fromUtf8(""))
        self.comboBox_distributor.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBox_distributor)
        self.gridLayout_10.addWidget(self.groupBox_distributor, 2, 0, 1, 4)
        self.groupBox_owner = QtGui.QGroupBox(self.tab_6)
        self.groupBox_owner.setObjectName(_fromUtf8("groupBox_owner"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_owner)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.comboBox_ownerOrganisation1 = QtGui.QComboBox(self.groupBox_owner)
        self.comboBox_ownerOrganisation1.setObjectName(_fromUtf8("comboBox_ownerOrganisation1"))
        self.comboBox_ownerOrganisation1.addItem(_fromUtf8(""))
        self.comboBox_ownerOrganisation1.addItem(_fromUtf8(""))
        self.comboBox_ownerOrganisation1.addItem(_fromUtf8(""))
        self.comboBox_ownerOrganisation1.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.comboBox_ownerOrganisation1, 1, 1, 1, 1)
        self.checkBox_owner1 = QtGui.QCheckBox(self.groupBox_owner)
        self.checkBox_owner1.setObjectName(_fromUtf8("checkBox_owner1"))
        self.checkBox_owner1.setChecked(True)
        self.gridLayout_11.addWidget(self.checkBox_owner1, 1, 0, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox_owner)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_11.addWidget(self.checkBox_2, 2, 0, 1, 1)
        self.comboBox_ownerOrganisation2 = QtGui.QComboBox(self.groupBox_owner)
        self.comboBox_ownerOrganisation2.setObjectName(_fromUtf8("comboBox_ownerOrganisation2"))
        self.comboBox_ownerOrganisation2.addItem(_fromUtf8(""))
        self.comboBox_ownerOrganisation2.addItem(_fromUtf8(""))
        self.comboBox_ownerOrganisation2.addItem(_fromUtf8(""))
        self.comboBox_ownerOrganisation2.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.comboBox_ownerOrganisation2, 2, 1, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_owner, 1, 0, 1, 4)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setEnabled(False)
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButton_validate = QtGui.QPushButton(self.tab_7)
        self.pushButton_validate.setObjectName(_fromUtf8("pushButton_validate"))
        self.gridLayout_2.addWidget(self.pushButton_validate, 3, 3, 1, 1)
        self.tableWidget_validation = QtGui.QTableWidget(self.tab_7)
        self.tableWidget_validation.setObjectName(_fromUtf8("tableWidget_validation"))
        self.tableWidget_validation.setColumnCount(8)
        self.tableWidget_validation.setRowCount(0)
        self.lineEdit_name = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_name.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_name.setObjectName(_fromUtf8("lineEdit_name"))
        self.gridLayout_2.addWidget(self.lineEdit_name, 1, 2, 1, 1)
        self.name = QtGui.QLabel(self.tab_ID)
        self.name.setObjectName(_fromUtf8("name"))
        self.gridLayout_2.addWidget(self.name, 1, 1, 1, 1)
        
        item = QtGui.QTableWidgetItem()
        self.tableWidget_validation.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_validation.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_validation.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_validation.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_validation.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_validation.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_validation.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_validation.setHorizontalHeaderItem(7, item)
        self.tableWidget_validation.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.gridLayout_2.addWidget(self.tableWidget_validation, 0, 0, 1, 3)
        self.pushButton_previous7 = QtGui.QPushButton(self.tab_7)
        self.pushButton_previous7.setObjectName(_fromUtf8("pushButton_previous7"))
        self.gridLayout_2.addWidget(self.pushButton_previous7, 2, 0, 1, 1)
        spacerItem26 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem26, 1, 0, 1, 1)
        spacerItem27 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem27, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_7, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 2)
        self.Title.setBuddy(self.lineEdit_title)
        self.Data_type.setBuddy(self.comboBox_Datatype)
        self.Abstract.setBuddy(self.textEdit_abstract)
        self.Tempend.setBuddy(self.dateEdit_tempend)
        self.date1.setBuddy(self.dateEdit_date)
        self.Tempstart.setBuddy(self.dateEdit_tempstart)
        self.Depth2.setBuddy(self.doubleSpinBox_depth2)
        self.Depth1.setBuddy(self.doubleSpinBox_depth1)
        self.North.setBuddy(self.doubleSpinBox_North)
        self.Coordinate_system.setBuddy(self.comboBox_ref_geo)
        self.South.setBuddy(self.doubleSpinBox_South1)
        self.East.setBuddy(self.doubleSpinBox_West)
        self.West.setBuddy(self.doubleSpinBox_East)
        self.Creation_date.setBuddy(self.dateEdit_creation_date)
        self.Subject_study.setBuddy(self.listWidget_subjectStudy2)
        self.Quality.setBuddy(self.lineEdit_quality)
        self.process.setBuddy(self.textEdit_process)
        self.Acces.setBuddy(self.comboBox_access)
        self.Citation.setBuddy(self.textEdit_Citation)
        self.Use_limitation.setBuddy(self.lineEdit_useLimitation)
        self.ResourceOrganisation.setBuddy(self.comboBox_resourcOrganisation)
        self.Organization_distributor.setBuddy(self.comboBox_distributor)

        self.retranslateUi(MainDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.pushButton_quit, QtCore.SIGNAL(_fromUtf8("clicked()")), MainDialog.close)
        QtCore.QObject.connect(self.pushButton_Next1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.tabWidget.show)
        QtCore.QMetaObject.connectSlotsByName(MainDialog)
        MainDialog.setTabOrder(self.tabWidget, self.lineEdit_title)
        MainDialog.setTabOrder(self.lineEdit_title, self.textEdit_abstract)
        MainDialog.setTabOrder(self.textEdit_abstract, self.comboBox_Datatype)
        MainDialog.setTabOrder(self.comboBox_Datatype, self.pushButton_Next1)
        MainDialog.setTabOrder(self.pushButton_Next1, self.comboBox_ref_geo)
        MainDialog.setTabOrder(self.comboBox_ref_geo, self.doubleSpinBox_North)
        MainDialog.setTabOrder(self.doubleSpinBox_North, self.doubleSpinBox_South1)
        MainDialog.setTabOrder(self.doubleSpinBox_South1, self.doubleSpinBox_West)
        MainDialog.setTabOrder(self.doubleSpinBox_West, self.doubleSpinBox_East)
        MainDialog.setTabOrder(self.doubleSpinBox_East, self.doubleSpinBox_depth1)
        MainDialog.setTabOrder(self.doubleSpinBox_depth1, self.doubleSpinBox_depth2)
        MainDialog.setTabOrder(self.doubleSpinBox_depth2, self.radioButton_temp)
        MainDialog.setTabOrder(self.radioButton_temp, self.dateEdit_tempstart)
        MainDialog.setTabOrder(self.dateEdit_tempstart, self.timeEdit_start)
        MainDialog.setTabOrder(self.timeEdit_start, self.dateEdit_tempend)
        MainDialog.setTabOrder(self.dateEdit_tempend, self.timeEdit_end)
        MainDialog.setTabOrder(self.timeEdit_end, self.radioButton_date)
        MainDialog.setTabOrder(self.radioButton_date, self.dateEdit_date)
        MainDialog.setTabOrder(self.dateEdit_date, self.timeEdit_date)
        MainDialog.setTabOrder(self.timeEdit_date, self.dateEdit_creation_date)
        MainDialog.setTabOrder(self.dateEdit_creation_date, self.pushButton_previous2)
        MainDialog.setTabOrder(self.pushButton_previous2, self.pushButton_next2)
        MainDialog.setTabOrder(self.pushButton_next2, self.listWidget_subjectStudy1)
        MainDialog.setTabOrder(self.listWidget_subjectStudy1, self.pushButton_subjectstudy_in)
        MainDialog.setTabOrder(self.pushButton_subjectstudy_in, self.listWidget_subjectStudy2)
        MainDialog.setTabOrder(self.listWidget_subjectStudy2, self.pushButton_subjectStudy_out)
        MainDialog.setTabOrder(self.pushButton_subjectStudy_out, self.listWidget_projectPhase1)
        MainDialog.setTabOrder(self.listWidget_projectPhase1, self.pushButton_projectPhasein)
        MainDialog.setTabOrder(self.pushButton_projectPhasein, self.listWidget_projectPhase2)
        MainDialog.setTabOrder(self.listWidget_projectPhase2, self.pushButton_projectPhaseout)
        MainDialog.setTabOrder(self.pushButton_projectPhaseout, self.listWidget_Location1)
        MainDialog.setTabOrder(self.listWidget_Location1, self.pushButton_locationin)
        MainDialog.setTabOrder(self.pushButton_locationin, self.listWidget_Location2)
        MainDialog.setTabOrder(self.listWidget_Location2, self.pushButton_locationout)
        MainDialog.setTabOrder(self.pushButton_locationout, self.listWidget_variable1)
        MainDialog.setTabOrder(self.listWidget_variable1, self.pushButton_variablein)
        MainDialog.setTabOrder(self.pushButton_variablein, self.listWidget_variable2)
        MainDialog.setTabOrder(self.listWidget_variable2, self.pushButton_variableout)
        MainDialog.setTabOrder(self.pushButton_variableout, self.pushButton_previous3)
        MainDialog.setTabOrder(self.pushButton_previous3, self.pushButton_next3)
        MainDialog.setTabOrder(self.pushButton_next3, self.listWidget_Format1)
        MainDialog.setTabOrder(self.listWidget_Format1, self.pushButton_Formatin)
        MainDialog.setTabOrder(self.pushButton_Formatin, self.listWidget_Format2)
        MainDialog.setTabOrder(self.listWidget_Format2, self.pushButton_formatout)
        MainDialog.setTabOrder(self.pushButton_formatout, self.lineEdit_quality)
        MainDialog.setTabOrder(self.lineEdit_quality, self.pushButton_previous4)
        MainDialog.setTabOrder(self.pushButton_previous4, self.pushButton_next4)
        MainDialog.setTabOrder(self.pushButton_next4, self.lineEdit_useLimitation)
        MainDialog.setTabOrder(self.lineEdit_useLimitation, self.comboBox_access)
        MainDialog.setTabOrder(self.comboBox_access, self.textEdit_Citation)
        MainDialog.setTabOrder(self.textEdit_Citation, self.pushButton_previous5)
        MainDialog.setTabOrder(self.pushButton_previous5, self.pushButton_next5)
        MainDialog.setTabOrder(self.pushButton_next5, self.checkBox_owner1)
        MainDialog.setTabOrder(self.checkBox_owner1, self.comboBox_ownerOrganisation1)
        MainDialog.setTabOrder(self.comboBox_ownerOrganisation1, self.checkBox_2)
        MainDialog.setTabOrder(self.checkBox_2, self.comboBox_ownerOrganisation2)
        MainDialog.setTabOrder(self.comboBox_ownerOrganisation2, self.comboBox_distributor)
        MainDialog.setTabOrder(self.comboBox_distributor, self.comboBox_resourcOrganisation)
        MainDialog.setTabOrder(self.comboBox_resourcOrganisation, self.pushButton_previous6)
        MainDialog.setTabOrder(self.pushButton_previous6, self.pushButton_next6)
        MainDialog.setTabOrder(self.pushButton_next6, self.tableWidget_validation)
        MainDialog.setTabOrder(self.tableWidget_validation, self.pushButton_previous7)
        MainDialog.setTabOrder(self.pushButton_previous7, self.pushButton_validate)
        MainDialog.setTabOrder(self.pushButton_validate, self.pushButton_quit)
        QtCore.QObject.connect(self.pushButton_Next1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.action_next1)
        QtCore.QObject.connect(self.pushButton_next2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.action_next2)
        QtCore.QObject.connect(self.pushButton_next3, QtCore.SIGNAL(_fromUtf8("clicked()")), self.action_next3)
        QtCore.QObject.connect(self.pushButton_next4, QtCore.SIGNAL(_fromUtf8("clicked()")), self.action_next4)
        QtCore.QObject.connect(self.pushButton_next5, QtCore.SIGNAL(_fromUtf8("clicked()")), self.action_next5)
        QtCore.QObject.connect(self.pushButton_next6, QtCore.SIGNAL(_fromUtf8("clicked()")), self.action_next6)
        QtCore.QObject.connect(self.pushButton_subjectStudy_out, QtCore.SIGNAL(_fromUtf8("clicked()")), self.arrowout_subject)
        QtCore.QObject.connect(self.pushButton_subjectstudy_in, QtCore.SIGNAL(_fromUtf8("clicked()")), self.arrowin_subject)
        QtCore.QObject.connect(self.pushButton_projectPhaseout, QtCore.SIGNAL(_fromUtf8("clicked()")), self.arrowout_project)
        QtCore.QObject.connect(self.pushButton_projectPhasein, QtCore.SIGNAL(_fromUtf8("clicked()")), self.arrowin_project)
        QtCore.QObject.connect(self.pushButton_locationin, QtCore.SIGNAL(_fromUtf8("clicked()")), self.arrowin_location)
        QtCore.QObject.connect(self.pushButton_locationout, QtCore.SIGNAL(_fromUtf8("clicked()")), self.arrowout_location)        
        QtCore.QObject.connect(self.pushButton_Formatin, QtCore.SIGNAL(_fromUtf8("clicked()")), self.arrowin_format)
        QtCore.QObject.connect(self.pushButton_formatout, QtCore.SIGNAL(_fromUtf8("clicked()")), self.arrowout_format)        
        QtCore.QObject.connect(self.pushButton_variablein, QtCore.SIGNAL(_fromUtf8("clicked()")), self.arrowin_variable)
        QtCore.QObject.connect(self.pushButton_variableout, QtCore.SIGNAL(_fromUtf8("clicked()")), self.arrowout_variable)
        QtCore.QObject.connect(self.pushButton_previous2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.action_previous2)
        QtCore.QObject.connect(self.pushButton_previous3, QtCore.SIGNAL(_fromUtf8("clicked()")), self.action_previous3)
        QtCore.QObject.connect(self.pushButton_previous4, QtCore.SIGNAL(_fromUtf8("clicked()")), self.action_previous4)
        QtCore.QObject.connect(self.pushButton_previous5, QtCore.SIGNAL(_fromUtf8("clicked()")), self.action_previous5)
        QtCore.QObject.connect(self.pushButton_previous6, QtCore.SIGNAL(_fromUtf8("clicked()")), self.action_previous6)
        QtCore.QObject.connect(self.pushButton_previous7, QtCore.SIGNAL(_fromUtf8("clicked()")), self.action_previous7)
        QtCore.QObject.connect(self.pushButton_validate, QtCore.SIGNAL(_fromUtf8("clicked()")), self.validate)
        
    def retranslateUi(self, MainDialog):
        MainDialog.setWindowTitle(_translate("MainDialog", "Metadata implementation for GeoNetwork", None))
        self.pushButton_quit.setText(_translate("MainDialog", "Quit", None))
        self.Language.setText(_translate("MainDialog", "Language", None))
        self.pushButton_Next1.setText(_translate("MainDialog", "Next >>", None))
        self.English.setText(_translate("MainDialog", "English", None))
        self.lineEdit_title.setPlaceholderText(_translate("MainDialog", "Title", None))
        self.Title.setText(_translate("MainDialog", "Title *", None))
        self.Data_type.setText(_translate("MainDialog", "Data type *", None))
        self.comboBox_Datatype.setItemText(0, _translate("MainDialog", "Dataset", None))
        self.comboBox_Datatype.setItemText(1, _translate("MainDialog", "Series", None))
        self.comboBox_Datatype.setItemText(2, _translate("MainDialog", "Services", None))
        self.Abstract.setText(_translate("MainDialog", "Abstract *", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ID), _translate("MainDialog", "Ressource identification", None))
        self.groupBox_time.setTitle(_translate("MainDialog", "Temporal extent", None))
        self.Tempend.setText(_translate("MainDialog", "End", None))
        self.date1.setText(_translate("MainDialog", "Date", None))
        self.Tempstart.setText(_translate("MainDialog", "Start", None))
        self.radioButton_date.setText(_translate("MainDialog", "Date **", None))
        self.radioButton_temp.setText(_translate("MainDialog", "Temporal extent **", None))
        self.groupBox_geo.setTitle(_translate("MainDialog", "Geographical extent", None))
        self.Depth2.setText(_translate("MainDialog", "To", None))
        self.Depth1.setText(_translate("MainDialog", "Depth extent : From", None))
        self.comboBox_ref_geo.setItemText(0, _translate("MainDialog", "WGS84", None))
        self.comboBox_ref_geo.setItemText(1, _translate("MainDialog", "Lambert 93", None))
        self.North.setText(_translate("MainDialog", "North *", None))
        self.Coordinate_system.setText(_translate("MainDialog", "Geographic coordinate system", None))
        self.degreeEast1.setText(_translate("MainDialog", "° E", None))
        self.South.setText(_translate("MainDialog", "South *", None))
        self.degreeNord2.setText(_translate("MainDialog", "° N", None))
        self.degreeast2.setText(_translate("MainDialog", "° E", None))
        self.degreeN1.setText(_translate("MainDialog", "° N", None))
        self.East.setText(_translate("MainDialog", "East *", None))
        self.West.setText(_translate("MainDialog", "West *", None))
        self.pushButton_next2.setText(_translate("MainDialog", "Next >>", None))
        self.pushButton_previous2.setText(_translate("MainDialog", "<< Previous", None))
        self.Creation_date.setText(_translate("MainDialog", "Creation date", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainDialog", "Spatial and temporal extent", None))
        self.ISO.setText(_translate("MainDialog", "ISO categories", None))
        self.Nongeodataset.setText(_translate("MainDialog", "Non geographic dataset", None))
        self.GeoscientificInformation.setText(_translate("MainDialog", "Geoscientific information", None))
        self.Theme.setText(_translate("MainDialog", "Thematic category", None))
        self.Subject_study.setText(_translate("MainDialog", "Subject study *", None))
        self.pushButton_subjectStudy_out.setText(_translate("MainDialog", "<<", None))
        self.pushButton_projectPhasein.setText(_translate("MainDialog", ">>", None))
        self.pushButton_previous3.setText(_translate("MainDialog", "<< Previous", None))
        self.pushButton_projectPhaseout.setText(_translate("MainDialog", "<<", None))
        self.pushButton_locationin.setText(_translate("MainDialog", ">>", None))
        self.Variable.setText(_translate("MainDialog", "Variables *", None))
        self.pushButton_next3.setText(_translate("MainDialog", "Next >>", None))
        self.Location.setText(_translate("MainDialog", "Location *", None))
        self.pushButton_variableout.setText(_translate("MainDialog", "<<", None))
        self.pushButton_subjectstudy_in.setText(_translate("MainDialog", ">>", None))
        self.pushButton_variablein.setText(_translate("MainDialog", ">>", None))
        __sortingEnabled = self.listWidget_variable1.isSortingEnabled()
        self.listWidget_variable1.setSortingEnabled(False)
        for i in range(0, len(variablechoice)-1):
            item = self.listWidget_variable1.item(i)
            item.setText(_translate("MainDialog", variablechoice[i], None)) 
            

        self.listWidget_variable1.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_subjectStudy1.isSortingEnabled()
        self.listWidget_subjectStudy1.setSortingEnabled(False)
        ##
        for i in range(0, len(subjectchoice)-1):
            item = self.listWidget_subjectStudy1.item(i)
            item.setText(_translate("MainDialog", subjectchoice[i], None))                    
        ##

        self.listWidget_subjectStudy1.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_projectPhase1.isSortingEnabled()
        self.listWidget_projectPhase1.setSortingEnabled(False)
        ##
        for i in range(0, len(projectchoice)-1):
            item = self.listWidget_projectPhase1.item(i)
            item.setText(_translate("MainDialog", projectchoice[i], None)) 
        ## 

        self.listWidget_projectPhase1.setSortingEnabled(__sortingEnabled)
        self.pushButton_locationout.setText(_translate("MainDialog", "<<", None))
        self.Project_phase.setText(_translate("MainDialog", "Project phase *", None))
        __sortingEnabled = self.listWidget_Location1.isSortingEnabled()
        self.listWidget_Location1.setSortingEnabled(False)
        ##
        for i in range(0, len(locationchoice)-1):
            item = self.listWidget_Location1.item(i)
            item.setText(_translate("MainDialog", locationchoice[i], None)) 
        ##    
        self.listWidget_Location1.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainDialog", "Keywords", None))
        self.Format.setText(_translate("MainDialog", "Format *", None))
        self.pushButton_next4.setText(_translate("MainDialog", "Next >>", None))
        __sortingEnabled = self.listWidget_Format1.isSortingEnabled()
        self.listWidget_Format1.setSortingEnabled(False)
        ##
        for i in range(0, len(formatchoice)-1):
            item = self.listWidget_Format1.item(i)
            item.setText(_translate("MainDialog", formatchoice[i], None))            
        self.listWidget_Format1.setSortingEnabled(__sortingEnabled)
        self.pushButton_Formatin.setText(_translate("MainDialog", ">>", None))
        self.Quality.setText(_translate("MainDialog", "Quality", None))
        self.process.setText(_translate("MainDialog", "Processing steps", None))
        self.pushButton_previous4.setText(_translate("MainDialog", "<< Previous", None))
        self.pushButton_formatout.setText(_translate("MainDialog", "<<", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainDialog", "Quality", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainDialog", "Processing", None))
        self.pushButton_next5.setText(_translate("MainDialog", "Next >>", None))
        self.Acces.setText(_translate("MainDialog", "Access contraints *", None))
        self.Citation.setText(_translate("MainDialog", "Citation", None))
        self.pushButton_previous5.setText(_translate("MainDialog", "<< Previous", None))
        self.Use_limitation.setText(_translate("MainDialog", "Use limitation", None))
        self.comboBox_access.setItemText(0, _translate("MainDialog", "Restricted", None))
        self.comboBox_access.setItemText(1, _translate("MainDialog", "Embargo", None))
        self.comboBox_access.setItemText(2, _translate("MainDialog", "Public", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainDialog", "Contraints", None))
        self.groupBox_resourceContact.setTitle(_translate("MainDialog", "Resource contact", None))
        self.ResourceOrganisation.setText(_translate("MainDialog", "Organization", None))
        self.comboBox_resourcOrganisation.setItemText(0, _translate("MainDialog", "EOST/ IPGS", None))
        self.comboBox_resourcOrganisation.setItemText(1, _translate("MainDialog", "GEIE", None))
        self.comboBox_resourcOrganisation.setItemText(2, _translate("MainDialog", "BRGM", None))
        self.comboBox_resourcOrganisation.setItemText(3, _translate("MainDialog", "Es Géothermie", None))
        self.pushButton_next6.setText(_translate("MainDialog", "Next >>", None))
        self.pushButton_previous6.setText(_translate("MainDialog", "<< Previous", None))
        self.groupBox_distributor.setTitle(_translate("MainDialog", "Distributor", None))
        self.Organization_distributor.setText(_translate("MainDialog", "Organization", None))
        self.comboBox_distributor.setItemText(0, _translate("MainDialog", "EOST/ IPGS", None))
        self.comboBox_distributor.setItemText(1, _translate("MainDialog", "GEIE", None))
        self.comboBox_distributor.setItemText(2, _translate("MainDialog", "BRGM", None))
        self.comboBox_distributor.setItemText(3, _translate("MainDialog", "Es Géothermie", None))
        self.groupBox_owner.setTitle(_translate("MainDialog", "Owner of the data", None))
        self.comboBox_ownerOrganisation1.setItemText(0, _translate("MainDialog", "EOST/ IPGS", None))
        self.comboBox_ownerOrganisation1.setItemText(1, _translate("MainDialog", "GEIE", None))
        self.comboBox_ownerOrganisation1.setItemText(2, _translate("MainDialog", "BRGM", None))
        self.comboBox_ownerOrganisation1.setItemText(3, _translate("MainDialog", "Es Géothermie", None))
        self.checkBox_owner1.setText(_translate("MainDialog", "Organization1", None))
        self.checkBox_2.setText(_translate("MainDialog", "Organization1", None))
        self.comboBox_ownerOrganisation2.setItemText(0, _translate("MainDialog", "EOST/ IPGS", None))
        self.comboBox_ownerOrganisation2.setItemText(1, _translate("MainDialog", "GEIE", None))
        self.comboBox_ownerOrganisation2.setItemText(2, _translate("MainDialog", "BRGM", None))
        self.comboBox_ownerOrganisation2.setItemText(3, _translate("MainDialog", "Es Géothermie", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainDialog", "Contacts", None))
        self.name.setText(_translate("MainDialog", "Saving name", None))
        self.pushButton_validate.setText(_translate("MainDialog", "Validate", None))
        item = self.tableWidget_validation.horizontalHeaderItem(0)
        item.setText(_translate("MainDialog", "Title", None))
        item = self.tableWidget_validation.horizontalHeaderItem(1)
        item.setText(_translate("MainDialog", "Abstract", None))
        item = self.tableWidget_validation.horizontalHeaderItem(2)
        item.setText(_translate("MainDialog", "Start time", None))
        item = self.tableWidget_validation.horizontalHeaderItem(3)
        item.setText(_translate("MainDialog", "End Time", None))
        item = self.tableWidget_validation.horizontalHeaderItem(4)
        item.setText(_translate("MainDialog", "North", None))
        item = self.tableWidget_validation.horizontalHeaderItem(5)
        item.setText(_translate("MainDialog", "West", None))
        item = self.tableWidget_validation.horizontalHeaderItem(6)
        item.setText(_translate("MainDialog", "South", None))
        item = self.tableWidget_validation.horizontalHeaderItem(7)
        item.setText(_translate("MainDialog", "East", None))
        self.pushButton_previous7.setText(_translate("MainDialog", "<< Previous", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainDialog", "Validation", None))
        
    def action_next1(self):
        "Action du bouton next de tab ID"
        global title, abstract, data_type
        title=self.lineEdit_title.text()
        abstract=self.textEdit_abstract.toPlainText()
        data_type=self.comboBox_Datatype.currentText()
        if title=='':
            e = QtGui.QMessageBox()
            e.setWindowTitle('Error')
            e.setText('Please enter a title')
            e.exec_()
        elif abstract=='':
            f = QtGui.QMessageBox()
            f.setWindowTitle('Error')
            f.setText('Please enter an abstract')
            f.exec_()
        else:
            self.Next(self.tab_ID, self.tab_2, 1)            
        
    def action_next2(self):
        "Action du bouton next du tab 2"
        global georef, North, South, East, West, Depth1, Depth2, date, T1, T2, Creation_date,  h2
        georef=self.comboBox_ref_geo.currentText()
        North=self.doubleSpinBox_North.value()
        South=self.doubleSpinBox_South1.value()
        East=self.doubleSpinBox_East.value()
        West=self.doubleSpinBox_West.value()
        Depth1=self.doubleSpinBox_depth1.value()
        Depth2=self.doubleSpinBox_depth2.value()
        creation_date=[str(self.dateEdit_creation_date.date().year()),str(self.dateEdit_creation_date.date().month()), str(self.dateEdit_creation_date.date().day())]
        Creation_date=creation_date[0]+'-'+creation_date[1]+'-'+creation_date[2]
        if self.radioButton_temp.isChecked()==1:
            t1=self.dateEdit_tempstart.date().toString('dd-MM-yyyy')
            h1=self.timeEdit_start.time().toString('hh:mm:ss')
            T1=t1+'T'+h1
            t2=self.dateEdit_tempend.date().toString('dd-MM-yyyy')
            h2=self.timeEdit_end.time().toString('hh:mm:ss')
            T2=t2+'T'+h2
         
            if T1>=T2:
                g = QtGui.QMessageBox()
                g.setWindowTitle('Error')
                g.setText('Please the start date should be lower than the end date')
                g.exec_()
            else:
                T3=1
        elif self.radioButton_date.isChecked()==1:
            t1=[str(self.dateEdit_date.date().year()),str(self.dateEdit_date.date().month()),str(self.dateEdit_date.date().day())]
            T1=t1[0]+'-'+t1[1]+'-'+t1[2]
            T2='0'
            T3=1
        if North<=South:
            e = QtGui.QMessageBox()
            e.setWindowTitle('Error')
            e.setText('North value should be higher than the South value')
            e.exec_()  
        elif West>=East:
            f = QtGui.QMessageBox()
            f.setWindowTitle('Error')
            f.setText('East value should be higher than the West value')
            f.exec_()
        elif self.radioButton_temp.isChecked()==0 and self.radioButton_date.isChecked()==0:
                d = QtGui.QMessageBox()
                d.setWindowTitle('Error')
                d.setText('Please choose date or a temporal extent')
                d.exec_()
        
        if North>South and West<East and T3==1:
            self.Next(self.tab_2, self.tab_3,2)
            
    def action_next3(self):
        "Action du bouton next du tab 3"
        global subject_Study, project_Phase, location, variables
        subject_Study=[]
        project_Phase=[]
        location=[]
        variables=[]
        for index in range(self.listWidget_subjectStudy2.count()):
            subject_Study.append(self.listWidget_subjectStudy2.item(index).text())            
        for index1 in range(self.listWidget_projectPhase2.count()):
            project_Phase.append(self.listWidget_projectPhase2.item(index1).text())           
        for index2 in range(self.listWidget_Location2.count()):
            location.append(self.listWidget_Location2.item(index2).text())           
        for index3 in range(self.listWidget_variable2.count()):
            variables.append(self.listWidget_variable2.item(index3).text())
        if subject_Study!=[] and variables!=[] and project_Phase!=[] and location!=[]:
            self.Next(self.tab_3, self.tab_4,3)
        else:
            d = QtGui.QMessageBox()
            d.setWindowTitle('Error')
            d.setText('Please choose at least one variable per proposition')
            d.exec_()
            
    def action_next4(self):
        "Action du bouton next du tab 4 quality"
        global format1, quality, process
        format1= []
        for index in range(self.listWidget_Format2.count()):
            format1.append(self.listWidget_Format2.item(index).text())
        quality=self.lineEdit_quality.text()
        process=self.textEdit_process.toPlainText()
        if format1!=[]:
            self.Next(self.tab_4, self.tab_5,4)
        else:
            d = QtGui.QMessageBox()
            d.setWindowTitle('Error')
            d.setText('Please enter a format')
            d.exec_()
        
    def action_next5(self):
        "Action du bouton next du tab 5 contraints"
        global use_lim, access, citation
        use_lim=self.lineEdit_useLimitation.text()
        access=self.comboBox_access.currentText()
        citation=self.textEdit_Citation.toPlainText()
        self.Next(self.tab_5, self.tab_6,5)

    
    def action_next6(self):
        "Action du bouton next du tab 6 contact"
        global owner1, owner2, distributor, resource_contact, result
        distributor=self.comboBox_distributor.currentText()
        resource_contact=self.comboBox_resourcOrganisation.currentText()
        result=[title, abstract,T1, T2, str(North), str(West), str(South), str(East)]
        self.Next(self.tab_6, self.tab_7,6)
        if self.checkBox_owner1.isChecked()==1 and self.checkBox_2.isChecked()==1:
            owner1=self.comboBox_ownerOrganisation1.currentText()
            owner2=self.comboBox_ownerOrganisation2.currentText()
        elif self.checkBox_owner1.isChecked()==1 and self.checkBox_2.isChecked()==0:
            owner1=self.comboBox_ownerOrganisation1.currentText()
            owner2=0
        elif self.checkBox_owner1.isChecked()==0 and self.checkBox_2.isChecked()==0:
            owner1=0
            owner2=0
        rowPosition=self.tableWidget_validation.rowCount()
        self.tableWidget_validation.insertRow(rowPosition)
        for i in range(0, self.tableWidget_validation.columnCount()):
            self.tableWidget_validation.setItem(rowPosition, i, QtGui.QTableWidgetItem(result[i]))
           
        
    def Next(self, tab1, tab2, tabnumber_tab1):
        tab1.hide()
        tab2.show()
        tab2.setEnabled(True)
        tab1.setEnabled(False)
        self.tabWidget.setCurrentIndex(tabnumber_tab1)
               
    def Previous(self, tab1, tab2, tabnumber_tab1):
        tab2.hide()
        tab1.show()
        tab2.setEnabled(False)
        tab1.setEnabled(True)
        self.tabWidget.setCurrentIndex(tabnumber_tab1)        
            
    def Arrow(self, W1, W2):
        item1=W1.currentItem()
        item2=W1.selectedItems()
        W2.addItem(item1.text())
        if not item2 :
            return
        for item in item2:
            W1.takeItem(W1.row(item))
        
    def arrowin_subject(self):
        self.Arrow(self.listWidget_subjectStudy1,self.listWidget_subjectStudy2)

    def arrowout_subject(self):
        self.Arrow(self.listWidget_subjectStudy2,self.listWidget_subjectStudy1)

    def arrowin_project(self):
        self.Arrow(self.listWidget_projectPhase1,self.listWidget_projectPhase2)

    def arrowout_project(self):
        self.Arrow(self.listWidget_projectPhase2,self.listWidget_projectPhase1)

    def arrowin_location(self):
        self.Arrow(self.listWidget_Location1,self.listWidget_Location2)
 
    def arrowout_location(self):
        self.Arrow(self.listWidget_Location2,self.listWidget_Location1)
        
    def arrowin_variable(self):
        self.Arrow(self.listWidget_variable1,self.listWidget_variable2)
 
    def arrowout_variable(self):
        self.Arrow(self.listWidget_variable2,self.listWidget_variable1)
        
    def arrowin_format(self):
        self.Arrow(self.listWidget_Format1,self.listWidget_Format2)
        
    def arrowout_format(self):
        self.Arrow(self.listWidget_Format2,self.listWidget_Format1)
        
    def action_previous2(self):
        self.Previous(self.tab_ID, self.tab_2,0)
    
    def action_previous3(self):
        self.Previous(self.tab_2, self.tab_3,1)

    def action_previous4(self):
        self.Previous(self.tab_3, self.tab_4,2)
        
    def action_previous5(self):
        self.Previous(self.tab_4, self.tab_5,3)
        
    def action_previous6(self):
        self.Previous(self.tab_5, self.tab_6,4)

    def action_previous7(self):
        self.Previous(self.tab_6, self.tab_7,5)
        rowPosition=self.tableWidget_validation.rowCount()
        self.tableWidget_validation.removeRow(rowPosition-1)

    def validate(self):
        global A, name
        name=self.lineEdit_name.text()
        if name!='':
            e = QtGui.QMessageBox()
            e.setWindowTitle('Information')
            e.setText('Do you want to continue ?')
            e.addButton( QtGui.QMessageBox.Yes)
            e.addButton( QtGui.QMessageBox.No)
            e.setDefaultButton(QtGui.QMessageBox.No)
            response=e.exec_()        
            if response==QtGui.QMessageBox.Yes:
                g = QtGui.QMessageBox()
                g.setWindowTitle('Information')
                g.setText('The xml file is created!')
                g.exec_() 
                B2d_XML.xml(A,title, abstract,data_type,North,East,South,West,Depth1,Depth2,T1,T2,Creation_date,subject_Study, project_Phase, location, variables, format1, quality,process, use_lim,access,citation, resource_contact, owner1, owner2, distributor, name)
                self.Next(self.tab_7, self.tab_ID,0)
                self.tab_2.setEnabled(True)
                self.tab_3.setEnabled(True)
                self.tab_4.setEnabled(True)
                self.tab_5.setEnabled(True)
                self.tab_6.setEnabled(True)
                A=A+1
            elif response==QtGui.QMessageBox.No:
                B2d_XML.xml(A,title, abstract,data_type,North,East,South,West,Depth1,Depth2,T1,T2,Creation_date,subject_Study, project_Phase, location, variables, format1, quality,process, use_lim,access,citation, resource_contact, owner1, owner2, distributor,name)
                h = QtGui.QMessageBox()
                h.setWindowTitle('Information')
                h.setText('The xml file has been created!')
                h.exec_()
                MainDialog.close()
        else:
            f = QtGui.QMessageBox()
            f.setWindowTitle('Error')
            f.setText('Please enter a name!')
            f.exec_()    
        

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainDialog = QtGui.QDialog()
    ui = Ui_MainDialog()
    ui.setupUi(MainDialog)
    MainDialog.show()
    sys.exit(app.exec_())

